name: Github Continuous Build and Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up Java Version v17
        uses: actions/setup-java@v1
        with:
          java-version: "17"

      - name: Maven Build Package
        run: mvn -B package --file backend/pom.xml

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
         run: railway up --build "mvn -B package --file pom.xml" --args "java -jar backend/target/backend-0.0.1-SNAPSHOT.jar"
