name: Github Continuous Build and Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Install Railway CLI
        run: npm i -g @railway/cli@3.0.22

      - name: Set up Java Version v17
        uses: actions/setup-java@v1
        with:
          java-version: "17"

      - name: Maven Build Package
        env:
         REDIS_PW: ${{ secrets.REDIS_PW }}
         GMAIL_PW: ${{ secrets.GMAIL_PW }}
         GITHUB_SECRET: ${{ secrets.OAUTH2_GITHUB_SECRET }}
         GITHUB_ID: ${{ secrets.OAUTH2_GITHUB_ID }}
         GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
         GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
         GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
         X_RapidAPI_Key: ${{ secrets.X_RapidAPI_Key }}
         MYSQLPASSWORD: ${{ secrets.MYSQLPASSWORD }}
        run: mvn -B package --file backend/pom.xml
    
      - name: Deploy to Railway
        run: railway up -d
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
