name: Github Continuous Build and Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Set up Java Version v17
        uses: actions/setup-java@v1
        with:
          java-version: "17"

      - name: Maven Build Package
        run: mvn -B package --file backend/pom.xml

  deploy:
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

       - name: Install Railway CLI
         run: npm i -g @railway/cli@3.0.8
    
       - name: Execute Railway link command
         run: railway link --environment production vttpminiproject02-augustine

      - name: Deploy to Railway
        env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --build "mvn -B package --file pom.xml" --args "java -jar backend/target/backend-0.0.1-SNAPSHOT.jar"
